### ISSUE TITLE
Home screen appears alongside sign in form

### ISSUE THREAD

**Issue by MurtajizMehdi** [rakeshpuppala2590/Twitter-clone#3]
Sign in form should be first thing user sees when visiting site; background should either be blurred out, or not accessible at all.

Should I create a separate page itself, and then once sign on is finished, push the page out? Maybe a function to handle different page views would come in handy?

**Comment by rakeshpuppala2590** [comment]
Background issue is fixed and as we discussed earlier we don't need to create a new page as it requires full page reload
